# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_learn',
                'doc_host': 'https://laprice.github.io',
                'git_url': 'https://github.com/laprice/nbdev_learn',
                'lib_path': 'nbdev_learn'},
  'syms': {'nbdev_learn.core': {'nbdev_learn.core.foo': ('core.html#foo', 'nbdev_learn/core.py')}}}
